### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by economyplusdev** [GreenFrogMCBE/GreenFrogMCBE#337]
- [yes ] I can confirm that this bug still persists in the most recent release of GreenFrogMCBE.
- [yes ] I can confirm that this bug isn't caused by plugins

## What's the issue?
The discord invite is invalid on the readme

[Please provide a detailed description of the problem]
The discord invite provided/prompts to users to join is invalid

**Comment by kotinash** [comment]
fixed
